{ config, ... }:
let
  theme = config.nixComputers.theme;
in
{
  flake.modules.hjem."feature/gtk" =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    lib.mkIf (lib.elem "gtk" config.nixComputers.profileFeatures) {
      packages = [
        pkgs.adw-gtk3
        pkgs.papirus-icon-theme
        pkgs.adwaita-icon-theme
      ];
      environment.sessionVariables = {
        GTK2_RC_FILES = "${config.directory}/.gtkrc-2.0";
        XCURSOR_THEME = theme.cursor.name;
        XCURSOR_SIZE = toString theme.cursor.size;
        XCURSOR_PATH = [
          "${config.directory}/.nix-profile/share/icons"
          "${config.directory}/.icons"
          "${config.directory}/.local/share/icons"
        ];
      };
      files = lib.mapAttrs (_: value: value // { clobber = true; }) {
        ".gtkrc-2.0".text = ''
          gtk-cursor-theme-name = "${theme.cursor.name}"
          gtk-cursor-theme-size = ${toString theme.cursor.size}
          gtk-font-name = "${theme.font.sans} ${toString theme.font.size}"
          gtk-icon-theme-name = "${theme.iconTheme}"
          gtk-theme-name = "adw-gtk3-dark"

        '';
        ".Xresources".text = ''
          Xcursor.size: ${toString theme.cursor.size}
          Xcursor.theme: ${theme.cursor.name}
        '';
        ".icons/Adwaita".source = "${pkgs.adwaita-icon-theme}/share/icons/Adwaita";
        ".icons/default/index.theme".text = ''
          [Icon Theme]
          Name=Default
          Comment=Default Cursor Theme
              Inherits=${theme.cursor.name}
        '';
      };
      xdg.config.files = lib.mapAttrs (_: value: value // { clobber = true; }) {
        "gtk-3.0/settings.ini".text = ''
          [Settings]
              gtk-cursor-theme-name=${theme.cursor.name}
              gtk-cursor-theme-size=${toString theme.cursor.size}
              gtk-font-name=${theme.font.sans} ${toString theme.font.size}
              gtk-icon-theme-name=${theme.iconTheme}
          gtk-theme-name=adw-gtk3-dark
        '';
        "gtk-4.0/settings.ini".text = ''
          [Settings]
              gtk-cursor-theme-name=${theme.cursor.name}
              gtk-cursor-theme-size=${toString theme.cursor.size}
              gtk-font-name=${theme.font.sans} ${toString theme.font.size}
              gtk-icon-theme-name=${theme.iconTheme}
          gtk-theme-name=adw-gtk3-dark
        '';
        "gtk-4.0/gtk.css".text = ''
          /**
           * GTK 4 reads the theme configured by gtk-theme-name, but ignores it.
           * It does however respect user CSS, so import the theme from here.
          **/
          @import url("file://${pkgs.adw-gtk3}/share/themes/adw-gtk3-dark/gtk-4.0/gtk.css");
        '';
        "fontconfig/conf.d/10-hm-fonts.conf".text = ''
          <?xml version='1.0'?>

          <!-- Generated by Hjem. -->

          <!DOCTYPE fontconfig SYSTEM 'urn:fontconfig:fonts.dtd'>
          <fontconfig>
            <description>Add fonts in the Hjem user profile</description>
                <dir>${config.directory}/.nix-profile/lib/X11/fonts</dir>
                <dir>${config.directory}/.nix-profile/share/fonts</dir>
          </fontconfig>
        '';
        "fontconfig/conf.d/10-hm-rendering.conf".text = ''
          <?xml version='1.0'?>

          <!-- Generated by Hjem. -->

          <!DOCTYPE fontconfig SYSTEM 'urn:fontconfig:fonts.dtd'>
          <fontconfig>
          </fontconfig>
        '';
        "fontconfig/conf.d/52-hm-default-fonts.conf".text = ''
          <?xml version='1.0'?>

          <!-- Generated by Hjem. -->

          <!DOCTYPE fontconfig SYSTEM 'urn:fontconfig:fonts.dtd'>
          <fontconfig>
          </fontconfig>
        '';
      };
      xdg.data.files = lib.mapAttrs (_: value: value // { clobber = true; }) {
        "icons/Adwaita".source = "${pkgs.adwaita-icon-theme}/share/icons/Adwaita";
        "icons/default/index.theme".text = ''
          [Icon Theme]
          Name=Default
          Comment=Default Cursor Theme
              Inherits=${theme.cursor.name}
        '';
      };
    };
}
